In [1]:
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('/content/weatherAUS.csv')
df

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,2017-06-25,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  object
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object
 10  WindDir3pm     141232 non-null  object
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  object
 22  RainTomorrow   142193 non-null  object
dtypes: float64(16), object(7)
memory usage: 25.5+ MB

In [3]:
df.isnull().any()

Date             False
Location         False
MinTemp           True
MaxTemp           True
Rainfall          True
Evaporation       True
Sunshine          True
WindGustDir       True
WindGustSpeed     True
WindDir9am        True
WindDir3pm        True
WindSpeed9am      True
WindSpeed3pm      True
Humidity9am       True
Humidity3pm       True
Pressure9am       True
Pressure3pm       True
Cloud9am          True
Cloud3pm          True
Temp9am           True
Temp3pm           True
RainToday         True
RainTomorrow      True
dtype: bool

In [4]:
df.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [5]:
df1=df.fillna(method='ffill')
df2=df1.fillna(method='bfill')
df2

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,12.0,12.3,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,2.0,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,12.0,12.3,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,8.0,2.0,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,12.0,12.3,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,8.0,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,12.0,12.3,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,8.0,2.0,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,12.0,12.3,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,10.0,10.7,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,8.0,7.0,10.1,22.4,No,No
145456,2017-06-22,Uluru,3.6,25.3,0.0,10.0,10.7,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,8.0,7.0,10.9,24.5,No,No
145457,2017-06-23,Uluru,5.4,26.9,0.0,10.0,10.7,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,8.0,7.0,12.5,26.1,No,No
145458,2017-06-24,Uluru,7.8,27.0,0.0,10.0,10.7,SE,28.0,SSE,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,2017-06-25,Uluru,14.9,27.0,0.0,10.0,10.7,SE,28.0,ESE,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,No

In [6]:
df2.isnull().sum()

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RainTomorrow     0
dtype: int64

In [7]:
from sklearn.preprocessing import OrdinalEncoder
enc=OrdinalEncoder()
enc.fit_transform(df2[['Location']])
df2[['Location']]=enc.fit_transform(df2[['Location']])
df2['Location']=df2['Location'].astype(float)
df2[['WindGustDir']]=enc.fit_transform(df2[['WindGustDir']])
df2['WindGustDir']=df2['WindGustDir'].astype(float)
df2[['WindDir9am']]=enc.fit_transform(df2[['WindDir9am']])
df2['WindDir9am']=df2['WindDir9am'].astype(float)
df2[['WindDir3pm']]=enc.fit_transform(df2[['WindDir3pm']])
df2['WindDir3pm']=df2['WindDir3pm'].astype(float)
df2[['RainToday']]=enc.fit_transform(df2[['RainToday']])
df2['RainToday']=df2['RainToday'].astype(float)
df2[['RainTomorrow']]=enc.fit_transform(df2[['RainTomorrow']])
df2['RainTomorrow']=df2['RainTomorrow'].astype(float)
df2.dtypes

Date              object
Location         float64
MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir      float64
WindGustSpeed    float64
WindDir9am       float64
WindDir3pm       float64
WindSpeed9am     float64
WindSpeed3pm     float64
Humidity9am      float64
Humidity3pm      float64
Pressure9am      float64
Pressure3pm      float64
Cloud9am         float64
Cloud3pm         float64
Temp9am          float64
Temp3pm          float64
RainToday        float64
RainTomorrow     float64
dtype: object

In [8]:
df2

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,2.0,13.4,22.9,0.6,12.0,12.3,13.0,44.0,13.0,...,71.0,22.0,1007.7,1007.1,8.0,2.0,16.9,21.8,0.0,0.0
1,2008-12-02,2.0,7.4,25.1,0.0,12.0,12.3,14.0,44.0,6.0,...,44.0,25.0,1010.6,1007.8,8.0,2.0,17.2,24.3,0.0,0.0
2,2008-12-03,2.0,12.9,25.7,0.0,12.0,12.3,15.0,46.0,13.0,...,38.0,30.0,1007.6,1008.7,8.0,2.0,21.0,23.2,0.0,0.0
3,2008-12-04,2.0,9.2,28.0,0.0,12.0,12.3,4.0,24.0,9.0,...,45.0,16.0,1017.6,1012.8,8.0,2.0,18.1,26.5,0.0,0.0
4,2008-12-05,2.0,17.5,32.3,1.0,12.0,12.3,13.0,41.0,1.0,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,41.0,2.8,23.4,0.0,10.0,10.7,0.0,31.0,9.0,...,51.0,24.0,1024.6,1020.3,8.0,7.0,10.1,22.4,0.0,0.0
145456,2017-06-22,41.0,3.6,25.3,0.0,10.0,10.7,6.0,22.0,9.0,...,56.0,21.0,1023.5,1019.1,8.0,7.0,10.9,24.5,0.0,0.0
145457,2017-06-23,41.0,5.4,26.9,0.0,10.0,10.7,3.0,37.0,9.0,...,53.0,24.0,1021.0,1016.8,8.0,7.0,12.5,26.1,0.0,0.0
145458,2017-06-24,41.0,7.8,27.0,0.0,10.0,10.7,9.0,28.0,10.0,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,0.0,0.0
145459,2017-06-25,41.0,14.9,27.0,0.0,10.0,10.7,9.0,28.0,2.0,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,0.0,0.0

In [9]:
x=df2.iloc[:,1:22].values
y=df2['RainTomorrow'].values
print(x)
print(y)

[[ 2.  13.4 22.9 ... 16.9 21.8  0. ]
 [ 2.   7.4 25.1 ... 17.2 24.3  0. ]
 [ 2.  12.9 25.7 ... 21.  23.2  0. ]
 ...
 [41.   5.4 26.9 ... 12.5 26.1  0. ]
 [41.   7.8 27.  ... 15.1 26.   0. ]
 [41.  14.9 27.  ... 15.  20.9  0. ]]
[0. 0. 0. ... 0. 0. 0.]

In [10]:
x=df2.iloc[:,1:22].values
y=df2['RainTomorrow'].values
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [11]:
#logistic regression
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression(random_state=0).fit(x_train,y_train)
y_pred=clf.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)
a=accuracy_score(y_test,y_pred)*100
a

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

84.10482896545977

In [12]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(x_train, y_train)
y_pred1=neigh.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred1)
a1=accuracy_score(y_test,y_pred1)*100
a1

82.14449397941752

In [13]:
#SVM 
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)
accuracy_score(y_test,y_pred)*100

84.65688929627933

In [14]:
# Naive Bias
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)
accuracy_score(y_test,y_pred)*100

78.79255031040373

In [15]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0)
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)
accuracy_score(y_test,y_pred)*100

78.16965959751677

In [16]:
# Random forest
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(x_train, y_train)
y_pred=clf.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)
accuracy_score(y_test,y_pred)*100

80.1758260072497

In [17]:
# After Comparing the accuracy score for each algorithm 
#The accuracy score for for SVM algorithm was found to be  maximum
#So SVM is a better algorithm for classification